### ISSUE TITLE
how to start script with systemd

### ISSUE THREAD

**Issue by MarkSau** [lmandres/GT06ScannerClient#1]
Hi,

after some fails i'm now able to start your script manually. My traccar server recieving the data and all ist fine.
Now I need to start the script with systemd, but something is wrong. Are you able to help me?

/etc/systemd/system/gpsd.service

`[Unit]
Description=GPS Service fuer Traccar
After=network.target

[Service]
Type=idle
User=pi
WorkingDirectory=/opt/GT06/GT06ScannerClient/
Environment=PYTHONPATH=/opt/GT06/GT06ScannerClient/venv/bin/python/
ExecStart=python runClient.py
Restart=on-failure

[Install]
WantedBy=multi-user.target`

syslog:

`Nov 23 20:19:45 MSHomeWohni systemd[1]: Started GPS Service fuer Traccar.
Nov 23 20:19:45 MSHomeWohni python[772]: Traceback (most recent call last):
Nov 23 20:19:45 MSHomeWohni python[772]:   File "runClient.py", line 3, in <module>
Nov 23 20:19:45 MSHomeWohni python[772]:     import GT06ScannerClient
Nov 23 20:19:45 MSHomeWohni python[772]:   File "/opt/GT06/GT06ScannerClient/GT06ScannerClient.py", line 4, in <module>
Nov 23 20:19:45 MSHomeWohni python[772]:     import crc_itu
Nov 23 20:19:45 MSHomeWohni python[772]: ImportError: No module named crc_itu
Nov 23 20:19:45 MSHomeWohni systemd[1]: gpsd.service: Main process exited, code=exited, status=1/FAILURE
Nov 23 20:19:45 MSHomeWohni systemd[1]: gpsd.service: Failed with result 'exit-code'.
Nov 23 20:19:46 MSHomeWohni systemd[1]: gpsd.service: Service RestartSec=100ms expired, scheduling restart.
Nov 23 20:19:46 MSHomeWohni systemd[1]: gpsd.service: Scheduled restart job, restart counter is at 5.
Nov 23 20:19:46 MSHomeWohni systemd[1]: Stopped GPS Service fuer Traccar.
Nov 23 20:19:46 MSHomeWohni systemd[1]: gpsd.service: Start request repeated too quickly.
Nov 23 20:19:46 MSHomeWohni systemd[1]: gpsd.service: Failed with result 'exit-code'.
`

thanks in advance

**Comment by lmandres** [comment]
@MarkSau , did you figure this out.  It looks like the requirements.txt file was not installed in the virtual environment.

**Comment by MarkSau** [comment]
ok...found the solution. have start the script in a wrong way...
i'm fine with

`[Unit]
Description=GPS Service fuer Traccar
After=network.target

[Service]
Type=idle
User=root
WorkingDirectory=/opt/GT06/GT06ScannerClient/
ExecStart=/opt/GT06/GT06ScannerClient/venv/bin/python /opt/GT06/GT06ScannerClient/runClient.py 
Restart=on-failure

[Install]
WantedBy=multi-user.target`
