### ISSUE TITLE
Not able to send gps data to server

### ISSUE THREAD

**Issue by dummyuser-123** [lmandres/GT06ScannerClient#7]
Hello,

I am trying to connect this client to an AWS server to check if the server is receiving GPS data. When I run the runClient script, it successfully sends and receives the login data, but it does not send any GPS data to the server afterward. I have also tested with the default config.xml, but it still fails to send GPS data.

I followed all the setup instructions provided in the README file. The only change I made in both cases (sending to my server and using the default configuration) was removing the <DisplaySettings> section from the config.xml. Everything else has remained unchanged. Also, I am running this code in windows setup. 

Could you please help me resolve this issue?

**Comment by lmandres** [comment]
Hi @dummyuser-123 .  Can you paste the contents of the <GPSSettings> section of the XML file?  I'm curious to see what you have for the <Port> entry.  Also, are you getting data from the GPS using a terminal like PuTTy?

**Comment by dummyuser-123** [comment]
Hello @lmandres, Sorry for the delayed response!!

This is how my XML file looks like:

```
<?xml version="1.0"?>
<ScannerSettings>
    <ScannerIDNumber>0466218603708364</ScannerIDNumber>
    <GT06ClientSettings>
        <Hostname>X.X.X.X</Hostname>
        <Port>5023</Port>
        <UpdateDelay>30</UpdateDelay>
    </GT06ClientSettings>
    <GPSSettings>
        <Port>COM1</Port>
        <Baud>4800</Baud>
    </GPSSettings>
</ScannerSettings>
```

Here, ScannerID is an random number that is similar to terminal ID of my device.

One other thing I would like to mention is that I am new to the IoT field, and I have been working on a GPS tracking device to retrieve GPS data using Python. However, sometimes I am unable to receive the GPS data from the device. While searching for a solution, I came across your repository and thought that if I could get GPS data from your code to my server, then the issue might be with my device.

I started your GT06ScannerClient on my local system and connected it to an AWS server. I was able to send and receive login data, but I couldn’t send GPS data. I also tried using a local server on my through PC, but it didn’t work either.

From your explanation, it seems I need to connect my device to my PC to send data to the server. Am I understanding this correctly? It would be very helpful if you could provide brief steps on configuration and connection because I have read the entire README, but I am still unable to send GPS data

**Comment by lmandres** [comment]
HI @dummyuser-123 .  It sounds like you are able to connect to AWS, but I'm wondering if the Port and/or Baud settings are correct.  On Windows, try installing a tool like PuTTY:

https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html

and connecting to your GPS device to receive a signal.  Try changing your Baud settings first.  You should get a text that contains something that starts with GPS or GNSS.  I don't have a GPS device connected to my computer right now, so I can't remember what the exact message looks like.

**Comment by dummyuser-123** [comment]
Currently, I have a setup that includes a PC (which runs the GT06ScannerClient) and an AWS server. There is no GPS device connected to my local PC. I am assuming that the GT06ScannerClient will send dummy GPS data to my AWS server after a successful login.

However, from your message, it seems like I need to connect my GPS device to my PC using PuTTY, and then my PC will send GPS data from the GPS device to the AWS server. From this, I understand that the GT06ScannerClient will act as a mediator between my GPS device and the AWS server. Am I understanding this correctly ?

Also, I am using this [gps device](https://pictortelematics.com/products/bike-gps-tracker/pt06-gps-tracker) for my usecase.

**Comment by lmandres** [comment]
Yes, except PuTTY is just used to test the GPS.  It is not necessary for the GT06ScannerClient to work.  Something like this should work:

https://www.aliexpress.us/item/3256805063349568.html

Also, the antenna should be outside for the GPS to work properly.

**Comment by dummyuser-123** [comment]
okay understood, Thank you for the help!!
